### ISSUE TITLE
Unable to find a specification for `Segment-Intercom` error message when running pod install

### ISSUE THREAD

**Issue by and-0-1** [segment-integrations/analytics-ios-integration-intercom#5]
I'm trying to install Segment-Intercom through pods as recommended on the documentation on my iOS app.
I'll post the pod install verbose to see is the trace helps to find the solutions

```
Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Moneypool`: (``)

Finding Podfile changes
  A Segment-Intercom
  - Analytics
  - Firebase

Resolving dependencies of `Podfile`
[!] Unable to find a specification for `Segment-Intercom`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/resolver.rb:461:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/resolver.rb:80:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/resolver.rb:72:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:742:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:739:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

[!] Automatically assigning platform ios with version 8.0 on target Moneypool because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
```

**Comment by and-0-1** [comment]
I'm using react native 0.42 and the latest release of Xcode as today
let me know if I can give any additional information
thanks for the help

**Comment by and-0-1** [comment]
Ok so fiddling a little with pods I managed to get pod to recognize Segment-Intercom but now I'm getting the next trace

```
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-Moneypool`: (``)

Finding Podfile changes
  A Segment-Intercom
  - Analytics
  - Firebase

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  A Intercom
  A Segment-Intercom
  - Analytics
  - Firebase
  - FirebaseAnalytics
  - FirebaseCore
  - FirebaseInstanceID
  - FirebaseMessaging
  - GoogleInterchangeUtilities
  - GoogleSymbolUtilities
  - GoogleToolboxForMac

Downloading dependencies

-> Using Analytics (3.6.1)

-> Using Firebase (3.10.0)

-> Using FirebaseAnalytics (3.6.0)

-> Using FirebaseCore (3.4.5)

-> Using FirebaseInstanceID (1.0.8)

-> Using FirebaseMessaging (1.2.1)

-> Using GoogleInterchangeUtilities (1.2.2)

-> Using GoogleSymbolUtilities (1.1.2)

-> Using GoogleToolboxForMac (2.1.0)

-> Installing Intercom (4.1.9)
  > Copying Intercom from `/Volumes/AlmacenamientoMac/Library/Caches/CocoaPods/Pods/Release/Intercom/4.1.9-c69c2` to
  `Pods/Intercom`

-> Installing Segment-Intercom (1.0.0-beta)
  > Copying Segment-Intercom from
  `/Volumes/AlmacenamientoMac/Library/Caches/CocoaPods/Pods/Release/Segment-Intercom/1.0.0-beta-f4942` to
  `Pods/Segment-Intercom`
  - Running pre install hooks
[!] The 'Pods-Moneypool' target has transitive dependencies that include static binaries: (/Volumes/AlmacenamientoMac/Desktop/moneypoolRepo/mobilRepo/mobile/ios/Pods/Intercom/Intercom/Intercom.framework)

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:434:in `block (2 levels) in verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:426:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:426:in `block in verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:423:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:423:in `verify_no_static_framework_transitive_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by toddgower-hiatus** [comment]
see https://github.com/segment-integrations/analytics-ios-integration-intercom/issues/6

**Comment by ladanazita** [comment]
Hi @andoni0305 , sorry for the delay. I would suggest what @toddgower  has and utilize the integration files into your project and natively rely on the Intercom pod.

Specifically, include these files manually:
https://github.com/segment-integrations/analytics-ios-integration-intercom/tree/master/Segment-Intercom/Classes

And do not include `Segment-Intercom`, rather use the native `Intercom` pod. This will allow you to rely directly on Intercom and remove the transitive dependency (i.e Segment sitting in the middle), but still leverage Segment since you will have the integration logic and `Analytics` installed. 

Let me know if this makes sense!
